---
---
# Tensorflow 2 - informacje elementarne
---
---

# Bibliografia

\begin{enumerate}
\item \textit{S. Raschka, V. Mirjalili}, Python Machine learning i deep learning. Biblioteki scikit-learn i TensorFlow 2,
Wydanie III, Helion, 2021.
\item \textit{A. Geron}, Uczenie maszynowe z uzyciem Scikit-Learn i TensorFlow. Helion, 2018.
\end{enumerate}

##### Spis treści:

[1. Typy](#1.Typy)

[2. Obiekty modyfikolwalne](#2.-Obiekty-modyfikowalne)


In [1]:
import tensorflow as tf
import numpy as np
np.set_printoptions(precision=3)

## 1. Typy 

### 1.1. Klasyczne typy języka Python


### 1.1.1.  Domyślnie zwykłe obiekty prostych typów liczbowych w tensorflow są identyczne jak w Pythonie

In [2]:
#zwykłe obiekty typów prostych języka python
a1 = 10 
print(type(a1))

a2 = 10.0 
print(type(a2))

a3 = "napis" 
print(type(a3))

a4 = True
print(type(a4))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


### 1.1.2. Analogicznie jest z podstawowymi typami kontenerowymi języka Python

In [3]:
a = [1,2,3]
b = (1,2,3)
c = {'a':1,'b':1.1,'c':True,'a':"xxx"}
print(type(a))
print(type(b))
print(type(c))

<class 'list'>
<class 'tuple'>
<class 'dict'>


## 1.2. Poprawne w Tensorflow jest jednak używanie jego własnych typów:  

<table style="border: 1px solid #e3e3e3;">
<th>type</th><th>tensorflow</th> 
<tbody>
<tr>
<td>floating point: </td>
<td>tf.float32, tf.float64</td>
</tr>
<tr>
<td>integers: </td>
<td>tf.int8, tf.int16, tf.int32, tf.int64</td>
</tr>
<tr><td>unsigned integers: </td>
<td>tf.uint8, tf.unit16</td>
</tr>
<tr>
<td>strings: </td><td>tf.string</td>
</tr>
<tr><td>booleans: </td>
<td>tf.bool</td>
</tr>
<tr>
<td>complex numbers: </td>
<td>tf.complex64, tf.complex128</td>
</tr>
<tr>
<td>integer with quantuized ops: </td>
<td>tf.qint8, tf.qint32, tf.quint8</td>
</tr>
</tbody>
</table>

Obiekty tych typów konstruuje się przez podstawowy typ biblioteki Tensorflow, czyli <b>Tensor</b>.

W ujęciu matematycznym możemy traktować tensory jako uogólnienie skalarów, wektorów,
macierzy itd. Mówiąc dokładniej, możemy zdefiniować <i>skalar</i> jako tensor rzędu 0, <i>wektor</i>
reprezentuje tensor rzędu 1., <i>macierz</i> jest tensorem rzędu 2, natomiast trójwymiarowe </i>kostki</i> są określane jako tensory rzędu 3. 

Ważne jest zwrócenie uwagi, że w module TensorFlow wartości są przechowywane w tablicach <i>NumPy</i>, a tensory zawierają
odwołania do tych tablic. W istocie to nawet typy podstawowe w TF są tożsame z analogicznymi typami NumPy. Można to prosto zauważyć, np.

In [4]:
print(tf.int64 == np.int64)

True


### 1.2.1. Typ Tensor i podstawowe operacje na tensorach

Tensor posiada dwie ważne własności (tożsame z odpowiednimi własnościami <i>ndarray</i> w NumPy)

- <i>kształt</i> (shape)
- <i>typ</i> (dtype)

Do tworzenia tensorów nie używamy zwykle konstruktora, ale różnych funkcji (zob. niżej)

Tensory można również tworzyć przez konwersje z obiektów NumPy, np.

In [5]:
a = np.array([1, 2, 3], dtype=np.int32) #tablica 
b = [4, 5, 6]

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [8]:
a.shape

(3,)

In [9]:
print(a)

[1 2 3]


In [10]:
type(b)

list

In [11]:
type(b[0])

int

In [12]:
print(b)

[4, 5, 6]


In [13]:
t_a = tf.convert_to_tensor(a) #konwersja na typ Tensor
t_b = tf.convert_to_tensor(b)

In [14]:
type(t_a)

tensorflow.python.framework.ops.EagerTensor

#### W Tensorflow 2.x obiekt typu <i>Tensor</i> jest w istocie obiektem typu <i>EagerTensor</i> - zob. [Tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor). 


In [15]:
t_a.shape

TensorShape([3])

In [16]:
t_a.dtype

tf.int32

In [17]:
t_a.numpy()

array([1, 2, 3], dtype=int32)

In [18]:
type(t_b)

tensorflow.python.framework.ops.EagerTensor

In [19]:
t_b.shape

TensorShape([3])

In [20]:
t_b.dtype

tf.int32

In [21]:
t_b.numpy()

array([4, 5, 6], dtype=int32)

In [22]:
t_ones = tf.ones((10,3))

In [23]:
t_ones

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [24]:
#za pomocą funkcji tf.cast() można zmieniać typ danych tensora do pożądanej postaci:
t_a_new = tf.cast(t_a, tf.int64)

In [25]:
t_a_new

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [26]:
t = tf.random.uniform(shape=(3, 5))
t

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.412, 0.495, 0.653, 0.643, 0.569],
       [0.557, 0.488, 0.856, 0.788, 0.345],
       [0.218, 0.323, 0.068, 0.826, 0.187]], dtype=float32)>

In [27]:
#Transponowanie tensora:
t_tr = tf.transpose(t)
t_tr

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.412, 0.557, 0.218],
       [0.495, 0.488, 0.323],
       [0.653, 0.856, 0.068],
       [0.643, 0.788, 0.826],
       [0.569, 0.345, 0.187]], dtype=float32)>

In [28]:
t = tf.zeros((30,))
t

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [29]:
#Zmiana rozmiaru tensora (np. z jednowymiarowego wektora do dwuwymiarowej tablicy):
t_reshape = tf.reshape(t, shape=(5, 6))
t_reshape

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [30]:
t = tf.zeros((1, 2, 1, 4, 1))
t

<tf.Tensor: shape=(1, 2, 1, 4, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.]]]]], dtype=float32)>

In [31]:
#Usuwanie niepotrzebnych wymiarów (wymiarów o rozmiarze 1, które są niepotrzebne):
t_sqz = tf.squeeze(t, axis=(2, 4))
t_sqz

<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

Przeprowadzanie operacji matematycznych na tensorach, zwłaszcza z zakresu algebry liniowej, jest niezbędne w procesie konstruowania większości modeli uczenia maszynowego. Powszechnie spotykane operacje to  iloczyn po współrzędnych, mnożenie macierzy czy obliczanie normy tensora.

In [32]:
#Dwa tensory losowe, jeden o rozkładzie jednostajnym w przedziale [–1, 1), a drugi o standardowym rozkładzie normalnym:
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5, 2),mean=0.0, stddev=1.0)

In [33]:
t1

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.67 ,  0.803],
       [ 0.262, -0.131],
       [-0.416,  0.285],
       [ 0.952, -0.13 ],
       [ 0.32 ,  0.21 ]], dtype=float32)>

In [34]:
t2

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.403, -1.088],
       [-0.063,  1.337],
       [ 0.712, -0.489],
       [-0.764, -1.037],
       [-1.252,  0.021]], dtype=float32)>

In [35]:
#Iloczyn po współrzędnych
t3 = tf.multiply(t1, t2)
t3

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.27 , -0.874],
       [-0.017, -0.175],
       [-0.296, -0.139],
       [-0.727,  0.135],
       [-0.401,  0.004]], dtype=float32)>

In [36]:
#średnie
t5 = tf.constant([[1., 2.], [3., 4.]])
t6 = tf.math.reduce_mean(t5)#średnia z wszystkich
t7 = tf.math.reduce_mean(t5,axis=0)#średnie z kolumn
t8 = tf.math.reduce_mean(t5,axis=1)#średnie z wierszy

In [37]:
t6

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [38]:
t7

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [39]:
t8

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [40]:
#sumy
t9 = tf.math.reduce_sum(t5)#suma z wszystkich
t10 = tf.math.reduce_sum(t5,axis=0)#suma z kolumn
t11 = tf.math.reduce_sum(t5,axis=1)#suma z wierszy

In [41]:
t9

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [42]:
t10

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 6.], dtype=float32)>

In [43]:
t11

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 7.], dtype=float32)>

In [44]:
#odchylenia standardowe
t12 = tf.math.reduce_std(t5)#z wszystkich
t13 = tf.math.reduce_std(t5,axis=0)#w kolumnach
t14 = tf.math.reduce_std(t5,axis=1)#w wierszach

In [45]:
t12

<tf.Tensor: shape=(), dtype=float32, numpy=1.1180340051651>

In [46]:
t13

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [47]:
t14

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5, 0.5], dtype=float32)>

In [48]:
t15= tf.constant([[1., 2., 3.], [4., 5.,6]])
t16 = tf.constant([[1., 1],[1, 1],[1., 1.]])

In [49]:
t15

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [50]:
t16

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [51]:
#iloczyn macierzowy
t17=tf.linalg.matmul(t15,t16)

In [52]:
t17

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  6.],
       [15., 15.]], dtype=float32)>

In [53]:
#iloczyn macierzowy z transpozycją obu macierzy
t18=tf.linalg.matmul(t15,t16, transpose_a=True,transpose_b=True,)

In [54]:
t18

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[5., 5., 5.],
       [7., 7., 7.],
       [9., 9., 9.]], dtype=float32)>

In [55]:
#p-norma tensora
norm_3 = tf.norm(t5, ord=3).numpy()#p=3
norm_2 = tf.norm(t5, ord=2, axis=1).numpy()#p=2, w wierszch

In [56]:
norm_3#100^(1/3)

np.float32(4.641589)

In [57]:
norm_2

array([2.236, 5.   ], dtype=float32)

In [58]:
t19= tf.constant([[1., 1., 2., 2.], [1., 1., 2., 2.],[3., 3., 4., 4.],[3., 3., 4., 4.]])

In [59]:
t19

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 2., 2.],
       [1., 1., 2., 2.],
       [3., 3., 4., 4.],
       [3., 3., 4., 4.]], dtype=float32)>

In [60]:
#podział tensora na mniejsze
t_splits_1 = tf.split(t19, num_or_size_splits=4)#wg wierszy na 4 części
t_splits_2 = tf.split(t19, num_or_size_splits=2)#wg wierszy na 2 części
t_splits_3 = tf.split(t19, num_or_size_splits=[1,3])#wg wierszy na 2 części, rozmairow 1 i 3

In [61]:
t_splits_1

[<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 1., 2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 1., 2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[3., 3., 4., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[3., 3., 4., 4.]], dtype=float32)>]

In [62]:
t_splits_2

[<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[1., 1., 2., 2.],
        [1., 1., 2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[3., 3., 4., 4.],
        [3., 3., 4., 4.]], dtype=float32)>]

In [63]:
t_splits_3

[<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 1., 2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 2., 2.],
        [3., 3., 4., 4.],
        [3., 3., 4., 4.]], dtype=float32)>]

In [64]:
#łączenie tensorów
t20 = tf.ones((3,))
t21 = tf.zeros((2,))
t23 = tf.concat([t20, t21], axis=0)
t24 = tf.concat([t15, t15], axis=0)
t25 = tf.concat([t15, t15], axis=1)

In [65]:
t23

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 1., 1., 0., 0.], dtype=float32)>

In [66]:
t24

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [67]:
t25

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6.]], dtype=float32)>

In [68]:
t26 = tf.constant([[1., 2., 3.]])
t27 = tf.constant([[10., 20., 30.]])

In [69]:
t26

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [70]:
t27

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[10., 20., 30.]], dtype=float32)>

In [71]:
#różnica pomiędzy stack i concat
t28=tf.stack([t26, t27], axis=1)#obiekt trójwymiarowy
t29=tf.concat([t26, t27], axis=1)#obiekt dwuwymiarowy

In [72]:
t28

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [10., 20., 30.]]], dtype=float32)>

In [73]:
t29

<tf.Tensor: shape=(1, 6), dtype=float32, numpy=array([[ 1.,  2.,  3., 10., 20., 30.]], dtype=float32)>

In [74]:
# Tensory utworzony przez funkcję tf.constant 
t30 = tf.constant([1, 2, 3])
t31 = tf.constant([[1.1, 2.2, 3.3], [4, 5, 6]])
t32 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t33 = tf.constant(["String_one", "String_two", "String_three"])
t34 = tf.constant([1.2, 2.3, 3.4], tf.float16, [3], 'N3')

print(type(t34))
print(t30)
print(t31)
print(t32)
print(t33)
print(t34)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1.1 2.2 3.3]
 [4.  5.  6. ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor([b'String_one' b'String_two' b'String_three'], shape=(3,), dtype=string)
tf.Tensor([1.2 2.3 3.4], shape=(3,), dtype=float16)


In [75]:
a = tf.gather(t30, 1) # utworzenie tensora ze składowej innego tensora
a

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## 1.3 Grafy obliczeniowe w TF1 i TF2 oraz wydajność ich kodów

w TF1 dane  trzeba było ulokować w <b>statycznym grafie</b> korzystając z <b>sesji</b> (Session). W TF2 dymyślnie działa mechanizm <b>wczesnego wykonania</b> (eager execution), a mechanizm sesji zniknął. Zaletą takiego rozwiązania jest uproszczenie kodu tworzenia modeli, natomiast wadą obniżenie wydajności (statystycznie razy 2 - ma na to wpływ również niezbyt doskonała integracja biblioteki keras jako modułu tensorflow).  

W ogólności zasadą koncepcyjną pisania kodu w TF2 jest jego podział na wiele małych funkcji, które mogą być one eksportowane i ponownie importowane w innych projektach. Ponadto funkcje takie   przez dekorator @tf.function mogą generować grafy statyczne, co ma zasaniczy wpływ na ich wydajność. 

Ponadto wskazane jest używanie zintegrowanego z TF2 modułu keras, który optymalizuje zarządzanie grupami zmiennych, pozwala je czasowo wyłączać z procesu uczenia (stan zamrożenia) oraz jeszcze bardziej kompaktuje kod.

Wczesne wykonanie kodu znaczenie upraszcza jego debugowanie, ale dubugowanie w TF2 jest również możliwe dla grafów statycznych (np. utworzonych przez @tf.function) przez funkcyjny przełącznik tf.config.run_functions_eagerly(True).


Zagadnienia te są dość dobrze opisane w dokumentacji - dobrze jest zajrzeć do

- [Effective tf2](https://www.tensorflow.org/guide/effective_tf2)

- [Better performance with tf.function](https://www.tensorflow.org/guide/function)

Można też używać gotowych narzędzi optymalizujących:

- [Optimize TensorFlow performance using the Profiler](https://www.tensorflow.org/guide/profiler)

- [TensorFlow graph optimization with Grappler](https://www.tensorflow.org/guide/graph_optimization)


## 2. Obiekty modyfikowalne


### 2.1. Informacje podstawowe

Obiekty utworzone przez funcję <i>tf.Variable()</i> są w Tensorflow modyfikowalne. Służą do tego ich funkcje z grupy <i>assign</i>



In [76]:
# Obiekt 
l1 = tf.Variable(initial_value=10, name="liczba")#podanie initial_value jest obligatoryjne
print(type(l1))
print(l1)


<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'liczba:0' shape=() dtype=int32, numpy=10>


In [77]:
l1.assign(20)#zmiana wartości

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=20>

In [78]:
l1.assign_add(20)#zmiana wartości przez dodanie
l1

<tf.Variable 'liczba:0' shape=() dtype=int32, numpy=40>

In [79]:
l1.assign_sub(20)#zmiana wartości przez odjęcie
l1

<tf.Variable 'liczba:0' shape=() dtype=int32, numpy=20>

In [80]:
l2 = tf.Variable([10,20], name="liczba")
print(type(l2))
print(l2)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'liczba:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>


In [81]:
l2[0].assign(30)#zmiana wartości składowej tensora
l2

<tf.Variable 'liczba:0' shape=(2,) dtype=int32, numpy=array([30, 20], dtype=int32)>

Zmienne zawierają atrybut trainable, którego domyślną wartością jest True. Wyspecjalizowane
interfejsy, takie jak Keras, za pomocą tego atrybutu zarządzają zmiennymi modyfikowalnymi
i niemodyfikowalnymi. Możesz zdefiniować niemodyfikowalny (w trakcie uczenia)
obiekt Variable następująco:

In [82]:
l3 = tf.Variable([1, 2, 3], trainable=False)
print(l3.trainable)

False


### 2.2. Koncepcje inicjalizowania zmiennych

W modelach sieci neuronowych inicjalizowanie parametrów modelu z losowymi
wagami jest niezbędne do złamania symetrii w fazie propagacji wstecznej, w przeciwnym wypadku wielowarstwowa sieć neuronowa nie byłaby lepsza od sieci jednowarstwowej, takiej jak
używana np. w regresji logistycznej. 

Podczas tworzenia obiektu Variable możemy wprowadzić
schemat inicjalizacji losowej. TensorFlow może generować liczby losowe za pomocą różnych rodzajów rozkładów; służy do tego klasa tf.random (więcej informacji znajdzieszna stronie [random]https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/random). 

Poniżej  przyjrzymy się niektórym standardowym metodom inicjalizacji, które są również
dostępne w interfejsie Keras (zob. [keras initializers]https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/
keras/initializers).

#### Inicjalizacja Xaviera (lub Glorota)

We wczesnym okresie rozwoju uczenia głębokiego zauważono, że inicjalizacja wag za pomocą losowego rozkładu
jednostajnego lub normalnego często prowadzi do słabej skuteczności modelu podczas uczenia.
W 2010 roku Xavier Glorot i Yoshua Bengio przyjrzeli się uważniej wpływowi inicjalizacji i zaproponowali
nowatorski, bardziej wszechstronny jej schemat, usprawniający uczenie sieci głębokich. Ogólny zamysł
inicjalizacji Xaviera polega na przybliżonym zrównoważeniu wariancji gradientów w różnych warstwach sieci.
Jeśli tego nie zrobimy, w trakcie uczenia uwaga może być zbytnio koncentrowana na jednej warstwie
kosztem innej warstwy.

Zgodnie z [artykułem](https://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf),  jeżeli chcemy inicjalizować
wagi z rozkładem jednostajnym (uniform, uzn. <b>U</b>), powinniśmy wybrać następujący przedział tego rozkładu:

$$
W\sim U\left(-\frac{\sqrt{6}}{\sqrt{n_i+n_{i+1}}},\frac{\sqrt{6}}{\sqrt{n_{i}+n_{i+1}}}\right)
$$
gdzie $n_i$ oznacza ilość neuronów w i-tej warstwie.

Poniższy kod pokazuje  jak można zdefiniować
obiekt Variable wewnątrz klasy bazowej tf.Module. Zdefiniujemy dwie zmienne: modyfikowalną
i niemodyfikowalną:



In [83]:
class MyModule(tf.Module):
    def __init__(self):
        init = tf.keras.initializers.GlorotNormal()
        self.w1 = tf.Variable(init(shape=(2, 3)), trainable=True)
        self.w2 = tf.Variable(init(shape=(1, 2)), trainable=False)
                
m = MyModule()
print('Wszystkie zmienne modułu: ', [v.shape for v in m.variables])
print('Zmienna modyfikowalna:   ', [v.shape for v in
                                 m.trainable_variables])

Wszystkie zmienne modułu:  [TensorShape([2, 3]), TensorShape([1, 2])]
Zmienna modyfikowalna:    [TensorShape([2, 3])]


Jak widać na powyższym listingu, stworzenie podklasy klasy tf.Module daje nam bezpośredni
dostęp do wszystkich zmiennych zdefiniowanych w danym obiekcie (tutaj w wystąpieniu
naszej niestandardowej klasy MyModule) poprzez atrybut .variables.

Kolejny kod pokazuje jak można korzystać ze zmiennych wewnątrz funkcji dekorowanej za
pomocą dekoratora tf.function. Podczas definiowania obiektu Variable wewnątrz standardowej
(niedekorowanej) funkcji można oczekiwać, że nowy obiekt Variable będzie tworzony i inicjalizowany
wraz z każdym wywołaniem funkcji. Jednak dekorator tf.function będzie starał się
wykorzystywać istniejący już obiekt Variable na podstawie śledzenia i tworzenia grafu. Tensorflow uniemożliwia więc tworzenie obiektu Variable wewnątrz funkcji dekorowanej i w konsekwencji
poniższy listing będzie powodował błąd:


In [84]:
## uruchomienie poniższego wiersza zakończy się komunikatem o błędzie
## ==> nie można tworzyć zmiennych wewnątrz funkcji dekorowanej

#@tf.function
#def f(x):
#    w = tf.Variable([1, 2, 3])

#f([1])

## ==> skutkuje błędem
## ValueError: tf.function-decorated function tried to create variables on non-first call.

Jednym ze sposobów uniknięcia tego problemu jest zdefiniowanie obiektu Variable poza funkcją dekorowaną i użycie go wewnątrz funkcji:

In [85]:
import tensorflow as tf

tf.random.set_seed(1)
w = tf.Variable(tf.random.uniform((3, 3)))

@tf.function
def compute_z(x):    
    return tf.matmul(w, x)

x = tf.constant([[1], [2], [3]], dtype=tf.float32)
tf.print(compute_z(x))

[[3.8610158]
 [2.94593048]
 [3.82629013]]
